export const API_BASE_URL = "http://localhost:4000";
export const API_ENDPOINT = {
    GET_DASHBOARD_DETAILS: "/dashboard/count/view/details",
    GET_CUSTOMER_DETAILS: "/customer/[customerId]/details/view",
    SAVE_CUSTOMER_LOAN_DETAILS: '/customer/gold/loan-details',
    GET_GOLD_ITEM_DETAILS: "/gold/view-items",
    UPDATE_CUSTOMER_RATINGS: "/customer/[customerId]/details/update",
    GET_CUSTOMER_GOLD_LOAN_DETAILS: "/customer/gold/loan-details/customer/[customerId]",
    GET_GOLD_DETAIL_TABLE: "/customer/gold/loan/[loanId]",
    LOGIN: "/member/login/api",
    GET_GOLD_BILL_HISTORY: "/billing/transaction/gold-loan/[goldLoanId]/bills",
    CHART_OF_ACCOUNT: "/chart/account/head/create",
    GET_ACCOUNT_HEAD_NAME: "/chart/account/",
    SAVE_PAYMENTS_RECIEPTS: "/chart/account/[chartId]/add-amount",
    GET_PAYMENTS_RECIEPTS: "/chart/account/view/payment-receipt ",
    SAVE_DESIGINATION_ROLE: "/member/role",
    SAVE_MEMBER_DETAILS: "/member/create",
    GET_DESIGNATION_ROLES: "/member/roles",
    SAVE_ADDITONAL_FEES: "/settings/additional/charges  ",
    GET_ADDITONAL_FEES: "/settings/view/additional/charges",
    SAVE_GOLDRATE: "/settings/rate",
    GET_GOLDRATE: "/settings/view/rate",
    SAVE_BANK_DETAILS: "/pledge/add-bank-details",
    SAVE_GOLD_ITEMS: "/gold/add-item",
    GET_BANK_DETAIL: "/pledge/view/bank-name",
    GET_PLEDGE_NUMBER: "/pledge",
    GET_PLEDGE_DETAILS: "/pledge/[pledgeId]",
    SAVE_PLEDGE_TRANSACTION: "/pledge/transaction",
    SEARCH_PLEDGE_DETAILS: "/pledge/view-all",
    GET_REPORTS: "/reports/all-loan",

}