export const ROUTES = {
    LOGIN: "/",
    HOME: "/home",
    GOLD_LOAN: "/gold-loan",
    CUSTOMER_GOLD_LOAN: "/gold-loan/:customerId",
    GOLD_TRANSACTION: "/gold-transaction",
    GL_LEDGER_REPORT: "/gl-ledger-report",
    GL_Transaction_Report: "/gl-transaction-report",
    GL_Customer_Details: "/glcustomerdetails",
    CHART_OF_ACCOUNTS: "/chartsofaccounts",
    PLEGDE_MASTER: "/pl-master",
    PLEDGE_TRANSACTION: "/pledge-transaction",
    FIXED_MASTER: "/fixed-master",
    FIXED_TRANSACTION: "/fixed-transaction",
}